# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.canvas = QtWidgets.QWidget(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(440, 70, 400, 400))
        self.canvas.setObjectName("canvas")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 468, 258))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.p5x_1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p5x_1.setMaximum(200)
        self.p5x_1.setObjectName("p5x_1")
        self.gridLayout.addWidget(self.p5x_1, 4, 1, 1, 1)
        self.p3x_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p3x_2.setMaximum(200)
        self.p3x_2.setObjectName("p3x_2")
        self.gridLayout.addWidget(self.p3x_2, 2, 2, 1, 1)
        self.p1x_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p1x_3.setMaximum(200)
        self.p1x_3.setObjectName("p1x_3")
        self.gridLayout.addWidget(self.p1x_3, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.rot_x = QtWidgets.QSlider(self.gridLayoutWidget)
        self.rot_x.setMaximum(200)
        self.rot_x.setOrientation(QtCore.Qt.Horizontal)
        self.rot_x.setObjectName("rot_x")
        self.gridLayout.addWidget(self.rot_x, 6, 1, 1, 1)
        self.p3x_1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p3x_1.setMaximum(200)
        self.p3x_1.setObjectName("p3x_1")
        self.gridLayout.addWidget(self.p3x_1, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.p1x_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p1x_2.setMaximum(200)
        self.p1x_2.setObjectName("p1x_2")
        self.gridLayout.addWidget(self.p1x_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.p4x_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p4x_3.setMaximum(200)
        self.p4x_3.setObjectName("p4x_3")
        self.gridLayout.addWidget(self.p4x_3, 3, 3, 1, 1)
        self.p4x_1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p4x_1.setMaximum(200)
        self.p4x_1.setObjectName("p4x_1")
        self.gridLayout.addWidget(self.p4x_1, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.p1x_1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p1x_1.setMaximum(200)
        self.p1x_1.setObjectName("p1x_1")
        self.gridLayout.addWidget(self.p1x_1, 0, 2, 1, 1)
        self.rot_y = QtWidgets.QSlider(self.gridLayoutWidget)
        self.rot_y.setMaximum(200)
        self.rot_y.setSingleStep(1)
        self.rot_y.setOrientation(QtCore.Qt.Horizontal)
        self.rot_y.setObjectName("rot_y")
        self.gridLayout.addWidget(self.rot_y, 5, 1, 1, 1)
        self.p2x_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p2x_3.setMaximum(200)
        self.p2x_3.setObjectName("p2x_3")
        self.gridLayout.addWidget(self.p2x_3, 1, 3, 1, 1)
        self.p4x_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p4x_2.setMaximum(200)
        self.p4x_2.setObjectName("p4x_2")
        self.gridLayout.addWidget(self.p4x_2, 3, 2, 1, 1)
        self.p2x_1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p2x_1.setMaximum(200)
        self.p2x_1.setObjectName("p2x_1")
        self.gridLayout.addWidget(self.p2x_1, 1, 1, 1, 1)
        self.p3x_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p3x_3.setMaximum(200)
        self.p3x_3.setObjectName("p3x_3")
        self.gridLayout.addWidget(self.p3x_3, 2, 3, 1, 1)
        self.p5x_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p5x_2.setMaximum(200)
        self.p5x_2.setObjectName("p5x_2")
        self.gridLayout.addWidget(self.p5x_2, 4, 2, 1, 1)
        self.draw = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.draw.setObjectName("draw")
        self.gridLayout.addWidget(self.draw, 6, 3, 1, 1)
        self.p5x_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p5x_3.setMaximum(200)
        self.p5x_3.setObjectName("p5x_3")
        self.gridLayout.addWidget(self.p5x_3, 4, 3, 1, 1)
        self.p2x_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.p2x_2.setMaximum(200)
        self.p2x_2.setObjectName("p2x_2")
        self.gridLayout.addWidget(self.p2x_2, 1, 2, 1, 1)
        self.proect = QtWidgets.QSlider(self.gridLayoutWidget)
        self.proect.setMaximum(1)
        self.proect.setOrientation(QtCore.Qt.Horizontal)
        self.proect.setObjectName("proect")
        self.gridLayout.addWidget(self.proect, 5, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 2, 1, 1)
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "P5"))
        self.label_6.setText(_translate("MainWindow", "Поворот отн. Y"))
        self.label_2.setText(_translate("MainWindow", "P2"))
        self.label.setText(_translate("MainWindow", "P1"))
        self.label_7.setText(_translate("MainWindow", "Поворот отн. X"))
        self.label_4.setText(_translate("MainWindow", "P4"))
        self.label_3.setText(_translate("MainWindow", "P3"))
        self.draw.setText(_translate("MainWindow", "Отрисовать прямую"))
        self.label_8.setText(_translate("MainWindow", "Проекция:"))
        self.menu.setTitle(_translate("MainWindow", "Кривая Безье"))
